import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/components/layout/layoutWrapper";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Skill 2 rural",
  // description: "Generated by create next app",
  icons: [
    {
      url: "/skill2rural-logo-image.svg",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" />
      </head>
      <body className="font-sf-pro font-[400]">
        <LayoutWrapper>{children}</LayoutWrapper>
        <ToastContainer />
      </body>
    </html>
  );
}
